name: stylinn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  video_player: ^2.8.2
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/images/brands/
    - assets/lottie/
    - assets/animations/
  
  # Removed manual font declarations as we're using Google Fonts now
